/* -------- functions ---------- */
def notifySlack(STATUS, COLOR) {
	slackSend (channel: '#my_channel', color: COLOR, message: STATUS+" : " +  "${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})")
}

pipeline {
  agent any 
  
  options {
    buildDiscarder(logRotator(daysToKeepStr: '7', numToKeepStr: '4'))
    disableConcurrentBuilds()
  }

  tools {
    maven 'maven'
  }
  
  environment {
      NEW_VERSION = "1.3.0"
      dockerRegistry="https://index.docker.io/v1/"
      tag="0.1.2"
      image="nexweb1/sample"
  }

  stages {
    stage("git-clone") {
      steps {
        script {
          notifySlack("Started:", "#FFFF00")
        }
        echo "Git clone from gitlab repository"
        git branch: 'dev', url: 'https://gitlab.com/nexweb/jenkins-handson.git'
      }
    }

    stage("build") {
      steps {
        echo "Building the application..."   
        sh "mvn clean package -Dmaven.testSkips=true "
      }
    }

    stage("inspect code") {
      steps {
        echo "inspecting the application..."
      }
    }

    stage("build and push image") {
      steps {
        echo "Building and push the image..."
        withCredentials ([
          usernamePassword(
            credentialsId: 'docker-credentials',
            usernameVariable: 'DOCKER_HUB_USER', 
            passwordVariable: 'DOCKER_HUB_PASSWORD'
          )
        ]) {
          echo "some credentials info : ${DOCKER_HUB_USER}, ${DOCKER_HUB_PASSWORD}"

					sh "podman login --tls-verify=false  --username ${DOCKER_HUB_USER} --password ${DOCKER_HUB_PASSWORD} ${dockerRegistry}"
					sh "podman build -f ./deployment/Dockerfile -t ${image}:${tag} ."
					sh "podman tag ${image}:${tag} ${image}:hello"
					sh "podman push ${image}:hello"    
        }
      }
    }

    stage("deploy") {
      steps {
        container('kubectl') {
          sh "kubectl delete deployments -n ${namespace} --selector=${selector_key}=${selector_val}"
        }
      }
    }
  }
  post {
    success {
      script {
        notifySlack("SUCCESSFUL: Job", "#00FF00")
      }
    }

    failure {
      script {
        notifySlack("Failed", "#FF0000")
      }
    }
  }

}