pipeline {
  agent any

  options {
    buildDiscarder(logRotator(daysToKeepStr: '7', numToKeepStr: '4'))
    disableConcurrentBuilds()
  }

  tools {
    maven 'maven'
  }
  
  environment {
      NEW_VERSION = "1.3.0"
      dockerRegistry="https://index.docker.io/v1/"
      tag="0.1.2"
      image="nexweb1/sample"
  }

  stages {
    stage("git-clone") {
      steps {
        echo "Git clone from gitlab repository"
        git branch: 'nexus', url: 'https://gitlab.com/nexweb/sample-service.git'
      }
    }

    stage("build") {
      steps {
        echo "Building the application..."   
        sh "mvn clean package -Dmaven.testSkips=true "
      }
    }

    stage("deploy jar to Nexus") {
      steps {
        echo "deploy the app to Nexus..."
        sh "mvn deploy"
      }
    }

    stage("build and push image") {
      steps {
        echo "Building and push the image..."
        withCredentials ([
          usernamePassword(
            credentialsId: 'docker-credentials',
            usernameVariable: 'DOCKER_HUB_USER', 
            passwordVariable: 'DOCKER_HUB_PASSWORD'
          )
        ]) {
          echo "some credentials info : ${DOCKER_HUB_USER}, ${DOCKER_HUB_PASSWORD}"

					sh "podman login --tls-verify=false --username ${DOCKER_HUB_USER} --password ${DOCKER_HUB_PASSWORD} ${dockerRegistry}"
					sh "podman build  -t ${image}:${tag} . -f deployment/Dockerfile"
					sh "podman tag ${image}:${tag} ${image}:hello"
					sh "podman push ${image}:hello"    
        }
      }
    }

    stage("deploy") {
      steps {
        echo "Deploy appliation..."
      }
    }
  }
}